test-py2.7:
  stage: test
  image: python:2.7
  script:
  - apt-get update -qy
  - pip install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=term
      
test-py3.5:
  stage: test
  image: python:3.5
  script:
  - apt-get update -qy
  - pip3 install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=html --cov-report=term
  artifacts:
    paths:
      - htmlcov
      
test-py3.6:
  stage: test
  image: python:3.6
  script:
  - apt-get update -qy
  - pip3.6 install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=term
      
test-py3.7:
  stage: test
  image: python:3.7
  script:
  - apt-get update -qy
  - pip install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=term
      
pages:
  stage: deploy
  dependencies:
    - test-py3.5
  script:
  - mv htmlcov/ public/
  only:
  - master
  artifacts:
    paths:
      - public