test-py2:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=term
      
test-py3:
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - export PYTHONPATH=/builds/cbeauchesne/CampBot:$PYTHONPATH
  - pytest --cov campbot --cov-report=html --cov-report=term
  artifacts:
    paths:
      - htmlcov
      
pages:
  stage: deploy
  dependencies:
    - test-py3
  script:
  - mv htmlcov/ public/
  only:
  - master
  artifacts:
    paths:
      - public