name: continuous-delivery

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'


jobs:
  build-and-publish:
    name: Publish release to Pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1

      - name: Build package
        run: |
          python --version
          pip install -r requirements.txt -r dev-requirements.txt
          python setup.py sdist bdist_wheel

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Test that package is published on Test PyPI
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --index-url https://test.pypi.org/simple/ --no-deps campbot

      - name: Check that version number from source is equal to release version number
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Tag name is ${GITHUB_REF##*/}"
          python -c "import campbot; print('Version is ' + campbot.__version__)"
          python -c "import campbot; exit(1 if campbot.__version__ != '${GITHUB_REF##*/}' else 0)"
      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
